"""Explicit Phase 1C extraction specs grounded in Canonical main.
Missing issuer evidence is represented as a gap, never model-filled.
"""
from .underwriting_extractor import extract_underwriting

SPECS = {
"601138.SH":{
 "security_id":"601138.SH","security_name":"工业富联","source_paths":["investment_os_runtime/30_STATE_CURRENT/30_RESEARCH/WP5_P0_EXTERNAL_REUNDERWRITE_CURRENT.json","investment_os_runtime/30_STATE_CURRENT/60_DECISIONS/WP5_INDUSTRIAL_FULIAN_TRIM_REVIEW_CURRENT.json"],
 "underwriting":{"business_economics":{"drivers":["AI server/network demand","order visibility","AI capex cycle"],"risk":"customer concentration/margin pressure"},"normalized_earnings_cashflow":{"state":"Q1 cash-flow recovery after weak 2025 conversion","fresh_h1_quality_review_required":True},"durability":{"state":"positive operating growth with cycle/concentration risk"},"balance_sheet_capital_allocation":None,"thesis":"Retain reduced observation position; fresh issuer earnings quality and valuation are required before any add or trim recommendation.","falsifiers":["AI server/order visibility decelerates materially","customer/pricing pressure compresses margin","cash flow again diverges materially from profit","AI capex enters sustained down-cycle","valuation rises without earnings upgrades"]},
 "valuation":{"status":"AVAILABLE_STALE","anchor":{"legacy_base_implied_price_rmb":65.510681,"legacy_base_expected_return":-0.05304017,"decision_anchor_date":"2026-08-10"},"framework":{"governed_add_hurdle":0.15,"stale_for_new_action":True},"scenarios":[]},
 "portfolio_context":{"canonical_action":"HOLD_600_SHARES_NO_ADD_NO_TRADE","quantity":600,"old_operating_alert_weight":0.041},
 "research_quality":{"completeness":"PARTIAL","evidence_gaps":["fresh H1 earnings-quality underwriting","fresh completed-close valuation/portfolio fit"]},
 "readiness":{"decision_readiness":"RESEARCH_ONLY","comparison_readiness":"READY_AFTER_REFRESH","refresh_requirements":["fresh H1/major primary-source review","fresh completed-close valuation"]}},
"605090.SH":{
 "security_id":"605090.SH","security_name":"九丰能源","source_paths":["investment_os_runtime/30_STATE_CURRENT/10_REAL_ACCOUNT/REAL_ACCOUNT_POSITIONS_CURRENT.json"],
 "underwriting":{"business_economics":None,"normalized_earnings_cashflow":None,"durability":None,"balance_sheet_capital_allocation":None,"thesis":None,"falsifiers":[]},
 "valuation":{"status":"UNAVAILABLE","anchor":None,"framework":None,"scenarios":[]},
 "portfolio_context":{"account":"REAL","quantity":9900,"mark_rmb":36.31,"mark_as_of":"2026-08-14","market_value_rmb":359469.0,"account_total_assets_rmb":819057.162038,"weight_of_total_assets":0.4388814562,"broker_verified":False,"diagnostic":"HIGH_SINGLE_NAME_CONCENTRATION_REUNDERWRITE_PRIORITY","concentration_is_automatic_sell_signal":False},
 "research_quality":{"completeness":"MATERIAL_EVIDENCE_GAP","evidence_gaps":["issuer-specific business economics absent from Phase 1C Canonical source set","normalized earnings/cash-flow underwriting absent","decision-grade valuation absent"]},
 "readiness":{"decision_readiness":"EVIDENCE_GAP","comparison_readiness":"NOT_READY","refresh_requirements":["issuer-specific primary-source re-underwrite","normalized earnings/cash-flow model","valuation framework"]}},
"HKEX:00669":{
 "security_id":"HKEX:00669","security_name":"TECHTRONIC IND","source_paths":["investment_os_runtime/30_STATE_CURRENT/60_DECISIONS/HKCU_TTI_00669_BUY_REVIEW_CURRENT.json","evidence/hkcu_p5c/HKCU_P5C_VALUATION_CONTEXT_20260807.csv"],
 "underwriting":{"business_economics":{"drivers":["MILWAUKEE/core-brand durability","H2 revenue/margin delivery"],"risks":["tariff/commodity/channel pressure","structural margin damage"]},"normalized_earnings_cashflow":{"official_h1_2026_eps_usd":0.405,"mechanical_annualized_eps_usd":0.81,"annualization_is_forecast":False,"monitor":"FCF conversion vs profit"},"durability":{"thesis_state":"PASS_WITH_PRICE_AND_SIZING_GATES"},"balance_sheet_capital_allocation":{"monitor":["balance-sheet quality","capital-return discipline","sensible repurchases"]},"thesis":"Operating evidence remains supportive, but valuation is fair-to-full and standard-lot sizing is mismatched to governed research sizing.","falsifiers":["H2 growth decelerates materially without transitory explanation","core-brand durability breaks","EBIT margin improvement reverses","FCF conversion deteriorates","balance-sheet quality deteriorates","material governance/audit/capital-allocation event"]},
 "valuation":{"status":"AVAILABLE_STALE","anchor":{"review_close_hkd":144.5,"review_date":"2026-08-11","historical_pe_context":21.6,"reference_pe_context":21.1},"framework":{"no_chase_above_hkd":140,"reopen_buy_review_at_or_below_hkd":135,"high_priority_review_at_or_below_hkd":130,"attractive_reunderwrite_at_or_below_hkd":125,"mandatory_fundamental_reunderwrite_below_hkd":120},"scenarios":[],"price_bands_are_research_gates":True},
 "portfolio_context":{"canonical_action":"WATCH_NO_TRADE_WAIT_FOR_PRICE_OR_POSITION_SIZING_GATE","standard_board_lot_shares":500,"board_lot_sizing_mismatch":True,"economic_review_weight_range":[0.01,0.02]},
 "research_quality":{"completeness":"COMPLETE_RESEARCH_ONLY","evidence_gaps":["fresh close/FX before comparison","broker/channel granularity before implementation"]},
 "readiness":{"decision_readiness":"RESEARCH_ONLY","comparison_readiness":"READY_AFTER_REFRESH","refresh_requirements":["fresh completed close and FX normalization"]}},
"000719.SZ":{
 "security_id":"000719.SZ","security_name":"中原传媒","source_paths":["investment_os_runtime/40_EVIDENCE_AND_LINEAGE/RESEARCH_QUEUE_D2/D2_RESEARCH_000719_20260813_R1.json","investment_os_runtime/40_EVIDENCE_AND_LINEAGE/RESEARCH_QUEUE_D2/D2_RESEARCH_000719_20260818_R2.json"],
 "underwriting":{"business_economics":{"core":"publishing/distribution franchise","publishing_gross_margin_pct":37.41,"distribution_gross_margin_pct":31.93,"materials_gross_margin_pct":5.85},"normalized_earnings_cashflow":{"normalized_earnings_rmb_bn_range":[1.25,1.35],"near_term_core_growth":"low-single-digit","cash_gate":"TTM CFO broadly at or above normalized profit","tax_policy_expiry":"2027-12-31"},"durability":{"state":"cash-rich defensive value with tax-policy dependency"},"balance_sheet_capital_allocation":{"2025_dividend_total_rmb_m":675.31,"payout_vs_adjusted_profit_pct":50.29},"thesis":"Headline growth overstates recurring growth; publishing/distribution economics support a defensive-value thesis while tax, working-capital and governance gates remain active.","falsifiers":["tax support lapses without offset","TTM CFO persistently below normalized earnings","receivables/inventory fail to unwind","investigation causes material operating/accounting/control/capital-allocation consequence"]},
 "valuation":{"status":"PARTIAL","anchor":None,"framework":{"normalized_eps_rmb_range":[1.22,1.32],"defensive_value_pe_max":8,"fair_watch_pe_range":[8,10],"growth_evidence_required_above_pe":11,"research_value_zone_rmb_range":[9.8,10.6]},"scenarios":[]},
 "portfolio_context":None,"research_quality":{"completeness":"COMPLETE_RESEARCH_ONLY","evidence_gaps":["fresh completed-close valuation","post-2027 tax outcome","working-capital unwind","governance investigation outcome"]},
 "readiness":{"decision_readiness":"RESEARCH_ONLY","comparison_readiness":"READY_AFTER_REFRESH","refresh_requirements":["fresh completed-close price/multiple","confirm no material governance thesis change"]}},
"002039.SZ":{
 "security_id":"002039.SZ","security_name":"黔源电力","source_paths":["investment_os_runtime/40_EVIDENCE_AND_LINEAGE/RESEARCH_QUEUE_D2/D2_RESEARCH_002039_20260813_R1.json"],
 "underwriting":{"business_economics":{"driver":"hydrology-driven hydro generation","2024_generation_100m_kwh":70.51,"2025_generation_100m_kwh":121.20,"cyclicality":"high hydrology sensitivity"},"normalized_earnings_cashflow":{"normal_water_earnings_rmb_m_range":[300,400],"dry_weak_case_rmb_m_range":[220,270],"wet_case_rmb_m":600,"normal_case_is_analyst_assumption":True,"2025_cfo_rmb_bn":2.4345},"durability":{"constraint":"leverage and hydrology volatility make wet-year run rate unsuitable as normalized base"},"balance_sheet_capital_allocation":{"2025_three_bucket_debt_rmb_bn":6.008,"2025_interest_expense_rmb_m":215.29,"normalized_sustainable_dividend_rmb_m_range":[105,180]},"thesis":"Defensive case depends on normal-water FCF, deleveraging and valuation discipline, not the exceptional wet-year result.","falsifiers":["normalized earnings below RMB300m without recovery","gross debt reverses upward materially","interest expense stops declining","dividend plus capex requires re-leveraging","valuation exceeds 15x normalized EPS without better economics"]},
 "valuation":{"status":"PARTIAL","anchor":{"market_snapshot_period":"2026-07","trailing_pe_approx":13,"dividend_yield_approx_pct":2.5},"framework":{"normalized_eps_rmb_range":[0.82,0.94],"research_invalidation_above_normalized_pe":15},"scenarios":[]},
 "portfolio_context":None,"research_quality":{"completeness":"COMPLETE_RESEARCH_ONLY","evidence_gaps":["longer basin hydrology series","fresh completed-close normalized valuation"]},
 "readiness":{"decision_readiness":"RESEARCH_ONLY","comparison_readiness":"READY_AFTER_REFRESH","refresh_requirements":["fresh normalized P/E","refresh hydrology/leverage if new disclosure"]}},
"301215.SZ":{
 "security_id":"301215.SZ","security_name":"中汽股份","source_paths":["investment_os_runtime/40_EVIDENCE_AND_LINEAGE/RESEARCH_QUEUE_D2/D2_RESEARCH_301215_20260818_R2.json"],
 "underwriting":{"business_economics":{"moat":"proving-ground network/scenario coverage","growth_mix":"Salt City ramp plus same-control consolidation; exact organic bridge unavailable"},"normalized_earnings_cashflow":None,"durability":{"risk":"customer concentration and unproven new-capacity economics"},"balance_sheet_capital_allocation":{"convertible_bond_rmb_bn":1.03904,"initial_conversion_price_rmb":5.99,"funding_runway":"improved but accretion vs dilution unproven"},"thesis":"Strategic testing demand may be attractive, but project-level realized economics are insufficient to underwrite new capacity.","falsifiers":["prolonged under-utilization","mature project return below 8-10% hurdle","rising concentration with weaker third-party demand","dilution without proportionate earnings accretion"]},
 "valuation":{"status":"UNAVAILABLE","anchor":None,"framework":{"analytical_ceiling":"retain R1 framework; financing completion alone cannot raise it"},"scenarios":[]},
 "portfolio_context":None,"research_quality":{"completeness":"MATERIAL_EVIDENCE_GAP","evidence_gaps":["project-level realized utilization","realized pricing/mix","incremental margin/EBITDA","mature ROIC/return series"]},
 "readiness":{"decision_readiness":"EVIDENCE_GAP","comparison_readiness":"NOT_READY","refresh_requirements":["next primary disclosure with utilization/project-benefit metrics"]}},
"000333.SZ":{
 "security_id":"000333.SZ","security_name":"美的集团","source_paths":["investment_os_runtime/30_STATE_CURRENT/30_RESEARCH/WP4_CORE2_RESEARCH_CURRENT.json","investment_os_runtime/30_STATE_CURRENT/30_RESEARCH/WP4B_CORE2_RESEARCH_CURRENT.json"],
 "underwriting":{"business_economics":{"role":"QUALITY_GLOBAL_INDUSTRIAL_CONSUMER_COMPOUNDER","drivers":["overseas OBM/localization","ToB growth","industrial technology recovery","capital return"]},"normalized_earnings_cashflow":{"2026_q1_adjusted_parent_profit_growth_pct":-14.02,"2026_q1_operating_cash_flow_rmb_bn":14.529165,"2026_q1_operating_cash_flow_growth_pct":1.45},"durability":{"state":"cash-generative platform; Q1 profit-quality slowdown needs validation"},"balance_sheet_capital_allocation":{"monitor":"M&A integration/shareholder return"},"thesis":"Global platform has cash-generation and shareholder-return capacity, but Q1 adjusted-profit weakness requires margin, tariff/localization and integration verification.","falsifiers":["core profit persistently lags revenue","localization fails to offset trade barriers","ToB M&A lowers returns/cash conversion","FCF/shareholder return remains below normal"]},
 "valuation":{"status":"PARTIAL","anchor":{"price_rmb":84.5,"pe_ttm":14.5717067586,"fcf_yield_pct":6.5421048038,"shareholder_yield_pct":5.0890372818,"source_state_as_of":"2026-07-26"},"framework":{"wp4b_driver_based_scenarios_complete":True,"scenario_payload_extractable_from_current_state":False},"scenarios":[]},
 "portfolio_context":{"candidate_core":True,"research_only":True},"research_quality":{"completeness":"PARTIAL","evidence_gaps":["2026 adjusted-profit/margin trend","tariff/localization impact","M&A/capital return","fresh portfolio context","extractable scenario valuation payload"]},
 "readiness":{"decision_readiness":"RESEARCH_ONLY","comparison_readiness":"READY_AFTER_REFRESH","refresh_requirements":["fresh completed close","surface/refresh scenario valuation payload","refresh decision-grade limitations"]}},
"600900.SH":{
 "security_id":"600900.SH","security_name":"长江电力","source_paths":["investment_os_runtime/30_STATE_CURRENT/30_RESEARCH/WP4_CORE2_RESEARCH_CURRENT.json","investment_os_runtime/30_STATE_CURRENT/30_RESEARCH/WP4B_CORE2_RESEARCH_CURRENT.json"],
 "underwriting":{"business_economics":{"role":"DEFENSIVE_INFRASTRUCTURE_CASH_YIELD","driver":"six-dam cascade hydro generation/dispatch","2026_h1_generation_growth_pct":4.81},"normalized_earnings_cashflow":{"2026_q1_adjusted_parent_profit_growth_pct":19.2,"2026_q1_operating_cash_flow_rmb_bn":11.7106630909,"profit_quality_gate":"separate operating profit from financial-asset gains"},"durability":{"state":"durable hydro cash-flow/dividend franchise with hydrology dispersion"},"balance_sheet_capital_allocation":{"2025_dividend_payout_pct":70.92,"2025_dividend_per_share_rmb":1.0,"monitor":"debt cost/dividend coverage"},"thesis":"Cascade hydro assets support durable cash flow/dividends, but hydrology dispersion, profit-quality composition and defensive valuation premium require discipline.","falsifiers":["generation below long-run normal","OCF cannot cover dividends/capex","net debt/interest burden rises","power-price policy weakens economics","high valuation compresses expected return"]},
 "valuation":{"status":"PARTIAL","anchor":{"price_rmb":28.9,"pe_ttm":19.5973488347,"fcf_yield_pct":6.1259390084,"cash_dividend_yield_pct":3.4602076125,"source_state_as_of":"2026-07-26"},"framework":{"wp4b_driver_based_scenarios_complete":True,"scenario_payload_extractable_from_current_state":False},"scenarios":[]},
 "portfolio_context":{"candidate_core":True,"research_only":True},"research_quality":{"completeness":"PARTIAL","evidence_gaps":["operating-profit vs fair-value gains","debt/interest and dividend coverage","hydrology/peer valuation refresh","fresh portfolio context","extractable scenario valuation payload"]},
 "readiness":{"decision_readiness":"RESEARCH_ONLY","comparison_readiness":"READY_AFTER_REFRESH","refresh_requirements":["fresh completed close","surface/refresh scenario valuation payload","refresh hydrology/debt-profit-quality gates"]}}
}

def build_all():
    return {security_id: extract_underwriting(spec) for security_id, spec in SPECS.items()}
