from __future__ import annotations

import json, shutil
from collections import Counter
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo
import pandas as pd
from scripts import fmdl4c_core as core

ROOT=Path(__file__).resolve().parents[1]
CFG=ROOT/'config/fmdl4c_reentry_controls.json'
TZ=ZoneInfo('Asia/Shanghai')


def require(cfg):
    e=cfg['entry_gate']; paths=[e[k] for k in ('pointer_path','release_path','decision_path','validation_path','graduation_decisions_path','research_objects_path')]+[cfg['composition_inputs']['fmdl4a_release_path']]
    missing=[p for p in paths if not (ROOT/p).exists()]
    if missing: return [f'MISSING_INPUT:{p}' for p in missing],None
    p,r,d,v,a=[core.read_json(ROOT/x) for x in (e['pointer_path'],e['release_path'],e['decision_path'],e['validation_path'],cfg['composition_inputs']['fmdl4a_release_path'])]
    dec=pd.read_csv(ROOT/e['graduation_decisions_path'],dtype={'symbol':str}); research=pd.read_csv(ROOT/e['research_objects_path'],dtype={'symbol':str})
    errors=[]
    if p.get('status')!=e['required_status'] or p.get('next_gate')!=e['required_next_gate'] or p.get('release_id')!=r.get('release_id'): errors.append('FMDL4B_POINTER')
    if r.get('status')!=e['required_status'] or d.get('status')!=e['required_status'] or d.get('hard_failures')!=[]: errors.append('FMDL4B_RELEASE_DECISION')
    if v.get('status')!='PASS' or v.get('hard_failures')!=[]: errors.append('FMDL4B_VALIDATION')
    if any(x.get('trade_authority')!='NONE' for x in (r,d,v,a)): errors.append('UPSTREAM_TRADE_AUTHORITY')
    if a.get('status')!='FMDL4A_RESEARCH_HANDOFF_AND_CANONICAL_ADAPTER_ACCEPTED' or a.get('release_id')!=cfg['composition_inputs']['release5_adapter_release_id']: errors.append('FMDL4A_BINDING')
    base=cfg['composition_inputs']['external_canonical_base']; abase=a.get('external_canonical_base',{})
    for k in ('package_name','release_sequence','package_sha256','status'):
        if abase.get(k)!=base.get(k): errors.append('BASE_IDENTITY:'+k)
    return errors, {'pointer':p,'release':r,'decision':d,'validation':v,'fmdl4a':a,'decisions':dec,'research':research}


def main():
    cfg=core.read_json(CFG); out=ROOT/cfg['overlay']['candidate_root']; shutil.rmtree(out,ignore_errors=True); out.mkdir(parents=True)
    ns=out/cfg['overlay']['namespace']; cs,ev,st=[ns/x for x in ('CORE_STATIC','EVIDENCE','STATE_CURRENT')]
    for p in (cs,ev,st): p.mkdir(parents=True)
    started=datetime.now(TZ); errors,src=require(cfg)
    if src is None:
        core.write_json(out/'FMDL4C_DECISION.json',{'program_id':'FMDL-4C','status':'FMDL4C_INVESTMENT_OS_REENTRY_AND_STATE_CONTROLS_REJECTED','hard_failures':errors,'trade_authority':'NONE'}); raise SystemExit(1)
    dec=src['decisions']; research=src['research']; grad=dec[dec.graduation_decision=='GRADUATED'].sort_values('overall_rank').reset_index(drop=True)
    ri=research.set_index('symbol').to_dict('index'); gs=set(grad.symbol.astype(str)); rs=set(cfg['reentry_routes']); missing_research=sorted(gs-set(ri)); route_errors=sorted(gs^rs)
    rv=str(src['release']['research_version']); created=str(src['decision'].get('generated_at') or started.isoformat(timespec='seconds'))
    transitions=[core.build_transition(row,ri.get(str(row['symbol']),{}),cfg,created_at=created,research_version=rv) for row in grad.to_dict('records')]
    t_errors=sum(bool(core.validate_transition(x,cfg)) for x in transitions); ti={x['symbol']:x for x in transitions}
    q=[]; cr=[]; sr=[]; rr=[]
    for row in grad.to_dict('records'):
        s=str(row['symbol']); route=cfg['reentry_routes'][s]; t=ti[s]; gates=json.dumps(route['open_gates'],ensure_ascii=False,sort_keys=True)
        q.append({'transition_id':t['transition_id'],'symbol':s,'name':route['name'],'queue_state':route['queue_state'],'route_class':route['route_class'],'priority':route['priority'],'research_id':row['research_id'],'research_version':rv,'evidence_ids_json':json.dumps(t['evidence_ids'],ensure_ascii=False,sort_keys=True),'open_gates_json':gates,'required_follow_on':route['required_follow_on'],'approval_state':t['approval_state'],'applied_to_overlay':True,'candidate_pool_membership_changed':False,'simulation_membership_changed':False,'real_account_membership_changed':False,'trade_authority':'NONE'})
        cr.append({'symbol':s,'name':route['name'],'queue_state':route['queue_state'],'candidate_router_decision':'REENTRY_REVIEW_QUEUE_ACCEPTED','existing_candidate_membership':'UNRESOLVED_EXTERNAL_BASE_NOT_BYTE_READABLE','actual_candidate_pool_action':cfg['mutation_policy']['actual_candidate_pool_action'],'open_gates_json':gates,'required_follow_on':route['required_follow_on'],'candidate_pool_mutation_authorized':False,'trade_authority':'NONE'})
        sr.append({'symbol':s,'name':route['name'],'simulation_router_decision':'BLOCKED_PENDING_CANDIDATE_OBSERVATION_AND_SIMULATION_DESIGN','simulation_action':cfg['mutation_policy']['actual_simulation_action'],'blocking_gates_json':json.dumps(['BASE_STATE_RECONCILIATION',*route['open_gates'],'SIMULATION_EXPERIMENT_DESIGN'],ensure_ascii=False,sort_keys=True),'simulation_mutation_authorized':False,'trade_authority':'NONE'})
        rr.append({'symbol':s,'name':route['name'],'real_account_router_decision':'BLOCKED_PENDING_FULL_REAL_ACCOUNT_GATE_SEQUENCE','real_account_action':cfg['mutation_policy']['actual_real_account_action'],'required_gate_sequence_json':json.dumps(cfg['real_account_gate_sequence'],ensure_ascii=False),'real_account_mutation_authorized':False,'user_confirmation_state':'NOT_REQUESTED','trade_authority':'NONE'})
    queue=pd.DataFrame(q).sort_values(['priority','symbol']); cand=pd.DataFrame(cr).sort_values('symbol'); sim=pd.DataFrame(sr).sort_values('symbol'); real=pd.DataFrame(rr).sort_values('symbol')
    before=[]; after=[{'symbol':x['symbol'],'queue_state':x['queue_state'],'transition_id':x['transition_id']} for x in queue.to_dict('records')]
    diff={'diff_version':'1.0.0','state_domain':cfg['state_domains']['overlay_reentry_queue'],'from_composition_sequence':5,'to_composition_sequence':6,'before_state_hash':core.stable_hash(before),'after_state_hash':core.stable_hash(after),'operation_count':len(after),'operations':[{'op':'UPSERT','key':x['symbol'],'transition_id':x['transition_id'],'to_state':x['queue_state'],'rollback_op':'DELETE_OVERLAY_KEY'} for x in after],'candidate_pool_mutation_count':0,'simulation_mutation_count':0,'real_account_mutation_count':0,'trade_authority':'NONE'}
    rollback={'proof_version':'1.0.0','rollback_scope':'REMOVE_FMDL4C_STATE_OVERLAY_ONLY','rollback_tokens':[x['rollback_token'] for x in transitions],'expected_post_rollback_hash':diff['before_state_hash'],'preserves_external_base':True,'preserves_fmdl4a_adapter':True,'preserves_fmdl4b_research':True,'failed_run_replaces_current':False,'failed_run_replaces_last_known_good':False,'trade_authority':'NONE'}
    bindings={'fmdl4b_release_id':src['release']['release_id'],'fmdl4b_research_version':rv,'fmdl4a_release_id':src['fmdl4a']['release_id'],'external_base_release_sequence':cfg['composition_inputs']['external_canonical_base']['release_sequence'],'external_base_sha256':cfg['composition_inputs']['external_canonical_base']['package_sha256'],'release6_composition_sequence':6}
    binding={'state_version':'1.0.0','composition_sequence':6,'composition_mode':cfg['composition_inputs']['composition_mode'],'bindings':bindings,'applied_state_domain':cfg['state_domains']['overlay_reentry_queue'],'applied_transition_count':len(transitions),'candidate_pool_mutation_count':0,'simulation_mutation_count':0,'real_account_mutation_count':0,'trade_register_mutation_count':0,'order_generation_count':0,'authority':cfg['authority'],'trade_authority':'NONE'}
    firewall={'firewall_version':'1.0.0','allowed':['CREATE_REENTRY_REVIEW_QUEUE','CREATE_VERSIONED_DIFF','CREATE_ROLLBACK_TOKEN','CREATE_ROUTER_DECISION'],'prohibited':['MUTATE_EXISTING_CANDIDATE_POOL','MUTATE_SIMULATION','MUTATE_REAL_ACCOUNT','CREATE_ORDER','EXECUTE_TRADE'],'candidate_pool_mutation_count':0,'simulation_mutation_count':0,'real_account_mutation_count':0,'order_generation_count':0,'trade_authority':'NONE'}
    core.write_json(cs/'FMDL4C_STATE_MUTATION_CONTROL_CONTRACT.json',{'contract_version':'1.0.0','state_domains':cfg['state_domains'],'mutation_policy':cfg['mutation_policy'],'real_account_gate_sequence':cfg['real_account_gate_sequence'],'authority':cfg['authority'],'trade_authority':'NONE'}); core.write_json(cs/'FMDL4C_AUTHORITY_FIREWALL.json',firewall)
    core.write_json(ev/'FMDL4C_RESEARCH_AND_EVIDENCE_BINDING.json',{'binding_version':'1.0.0','bindings':bindings,'graduated_symbols':sorted(gs),'research_ids':sorted(grad.research_id.astype(str)),'evidence_ids':sorted({z for x in transitions for z in x['evidence_ids']}),'trade_authority':'NONE'}); core.write_json(ev/'FMDL4C_LIMITATION_REGISTER.json',{'register_version':'1.0.0','limitations':cfg['controlled_limitations'],'trade_authority':'NONE'})
    core.write_jsonl(st/'FMDL4C_STATE_TRANSITIONS.jsonl',transitions); queue.to_csv(st/'FMDL4C_REENTRY_REVIEW_QUEUE.csv',index=False); cand.to_csv(st/'FMDL4C_CANDIDATE_ROUTER.csv',index=False); sim.to_csv(st/'FMDL4C_SIMULATION_ROUTER.csv',index=False); real.to_csv(st/'FMDL4C_REAL_ACCOUNT_ROUTER.csv',index=False); core.write_json(st/'FMDL4C_VERSIONED_DIFF.json',diff); core.write_json(st/'FMDL4C_ROLLBACK_AND_LKG_PROOF.json',rollback); core.write_json(st/'FMDL4C_BINDING_STATE.json',binding)
    files=[{'package_path':f"{cfg['overlay']['namespace']}/{p.relative_to(ns).as_posix()}",'source_path':str(p.relative_to(ROOT)),'sha256':core.sha256_file(p),'bytes':p.stat().st_size,'package_domain':p.relative_to(ns).parts[0]} for p in sorted(x for x in ns.rglob('*') if x.is_file())]
    manifest={'manifest_version':'1.0.0','composition_sequence':6,'composition_status':'RELEASE6_COMPOSED_CANONICAL_STATE_CANDIDATE','composition_mode':cfg['composition_inputs']['composition_mode'],'base_package':cfg['composition_inputs']['external_canonical_base'],'release5_adapter':{'release_id':bindings['fmdl4a_release_id'],'release_sequence':5},'release4b_research':{'release_id':bindings['fmdl4b_release_id'],'research_version':rv},'release6_state_overlay':{'namespace':cfg['overlay']['namespace'],'overlay_aggregate_sha256':core.stable_hash(files),'applied_transition_count':len(transitions),'state_domain':cfg['state_domains']['overlay_reentry_queue']},'files':files,'candidate_pool_mutation_count':0,'simulation_mutation_count':0,'real_account_mutation_count':0,'trade_authority':'NONE'}; manifest['aggregate_sha256']=core.stable_hash({'base':bindings['external_base_sha256'],'a':bindings['fmdl4a_release_id'],'b':bindings['fmdl4b_release_id'],'overlay':manifest['release6_state_overlay']['overlay_aggregate_sha256']}); core.write_json(out/'FMDL4C_RELEASE6_COMPOSITION_MANIFEST.json',manifest)
    z=out/'FMDL4C_RELEASE6_STATE_OVERLAY.zip'; core.deterministic_zip(ns,z); counts=Counter(queue.queue_state)
    metrics={'total_fmdl4b_decision_count':len(dec),'graduated_input_count':len(grad),'reentry_transition_count':len(transitions),'candidate_pool_reentry_review_count':counts['CANDIDATE_POOL_REENTRY_REVIEW_READY'],'shadow_track_reentry_review_count':counts['SHADOW_TRACK_REENTRY_REVIEW_READY'],'transition_validation_error_count':t_errors,'route_error_count':len(route_errors),'missing_research_binding_count':len(missing_research),'overlay_applied_transition_count':len(transitions),'candidate_pool_mutation_count':0,'simulation_mutation_count':0,'real_account_mutation_count':0,'order_generation_count':0,'trade_authority_error_count':sum(x['trade_authority']!='NONE' for x in transitions),'overlay_file_count':len(files),'elapsed_seconds':round((datetime.now(TZ)-started).total_seconds(),4)}
    a=cfg['acceptance']; checks={'ENTRY_GATE':not errors,'GRADUATED_INPUT_COUNT':len(grad)==cfg['entry_gate']['required_graduated_count'],'ROUTE_COVERAGE':not route_errors,'RESEARCH_BINDING':not missing_research,'STATE_TRANSITION_SCHEMA':t_errors==0,'REENTRY_TRANSITION_COUNT':len(transitions)==a['required_reentry_transition_count'],'CANDIDATE_REVIEW_COUNT':metrics['candidate_pool_reentry_review_count']==a['required_candidate_review_count'],'SHADOW_TRACK_COUNT':metrics['shadow_track_reentry_review_count']==a['required_shadow_track_count'],'VERSIONED_DIFF':diff['operation_count']==len(transitions) and diff['before_state_hash']!=diff['after_state_hash'],'ROLLBACK_AND_LKG':rollback['expected_post_rollback_hash']==diff['before_state_hash'] and rollback['preserves_external_base'],'ZERO_CANDIDATE_POOL_MUTATION':metrics['candidate_pool_mutation_count']==0,'ZERO_SIMULATION_MUTATION':metrics['simulation_mutation_count']==0,'ZERO_REAL_ACCOUNT_MUTATION':metrics['real_account_mutation_count']==0,'ZERO_ORDER_GENERATION':metrics['order_generation_count']==0,'ZERO_TRADE_AUTHORITY':metrics['trade_authority_error_count']==0}
    hard=errors+[k for k,v in checks.items() if not v]; hashes={'state_transitions':core.stable_hash([{k:v for k,v in x.items() if k!='created_at'} for x in sorted(transitions,key=lambda x:x['symbol'])]),'reentry_queue':core.semantic_frame_hash(queue,sort_by=('priority','symbol')),'candidate_router':core.semantic_frame_hash(cand),'simulation_router':core.semantic_frame_hash(sim),'real_account_router':core.semantic_frame_hash(real),'versioned_diff':core.stable_hash(diff),'rollback_and_lkg':core.stable_hash(rollback),'composition_manifest':core.stable_hash(manifest),'overlay_zip':core.sha256_file(z)}
    comp=core.stable_hash({'bindings':bindings,'semantic_hashes':hashes,'composition_sequence':6}); asof=str(research.as_of.dropna().iloc[0]) if 'as_of' in research and not research.as_of.dropna().empty else '2026-07-17'; rid=f"FMDL4C_{asof.replace('-','')}_{comp[:12]}"
    payload={'decision_version':'1.0.0','program_id':'FMDL-4C','release_id':rid,'generated_at':started.isoformat(timespec='seconds'),'status':cfg['exit_status'] if not hard else 'FMDL4C_INVESTMENT_OS_REENTRY_AND_STATE_CONTROLS_REJECTED','hard_failures':hard,'checks':[{'check_id':k,'status':'PASS' if v else 'FAIL'} for k,v in checks.items()],'metrics':metrics,'bindings':bindings,'semantic_hashes':hashes,'reentry_summary':{'candidate_pool_reentry_review_symbols':sorted(queue[queue.queue_state=='CANDIDATE_POOL_REENTRY_REVIEW_READY'].symbol),'shadow_track_reentry_review_symbols':sorted(queue[queue.queue_state=='SHADOW_TRACK_REENTRY_REVIEW_READY'].symbol),'simulation_admission_count':0,'real_account_admission_count':0,'applied_scope':'FMDL4C_REENTRY_REVIEW_QUEUE_ONLY'},'controlled_limitations':cfg['controlled_limitations'],'authority':cfg['authority'],'trade_authority':'NONE','next_gate':cfg['next_gate']}; core.write_json(out/'FMDL4C_DECISION.json',payload); print(json.dumps(payload,ensure_ascii=False,indent=2)); return 0 if not hard else 1

if __name__=='__main__': raise SystemExit(main())
